<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="OpenIddict.AspNetCore" Version="7.1.0" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" Version="7.1.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../Aspire/R2.ShopNet.ServiceDefaults/R2.ShopNet.ServiceDefaults.csproj" />
    <ProjectReference Include="../R2.ShopNet.Catalog.Application/R2.ShopNet.Catalog.Application.csproj" />
    <ProjectReference Include="../R2.ShopNet.Catalog.Infrastructure/R2.ShopNet.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="../../../Framework/R2.ShopNet.Framework.ServiceDiscovery/R2.ShopNet.Framework.ServiceDiscovery.csproj" />
    <ProjectReference Include="../../../Framework/R2.ShopNet.Framework.Configuration/R2.ShopNet.Framework.Configuration.csproj" />
  </ItemGroup>
</Project>