<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.0" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.3.0" />
    <PackageReference Include="OpenIddict.AspNetCore" Version="5.8.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../Aspire/R2.ShopNet.ServiceDefaults/R2.ShopNet.ServiceDefaults.csproj" />
    <ProjectReference Include="..\R2.ShopNet.Identity.Application\R2.ShopNet.Identity.Application.csproj" />
    <ProjectReference Include="..\R2.ShopNet.Identity.Infrastructure\R2.ShopNet.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Framework\R2.ShopNet.Framework.ServiceDiscovery\R2.ShopNet.Framework.ServiceDiscovery.csproj" />
    <ProjectReference Include="..\..\..\Framework\R2.ShopNet.Framework.Configuration\R2.ShopNet.Framework.Configuration.csproj" />
    <ProjectReference Include="..\..\..\Framework\R2.ShopNet.Framework.Logging\R2.ShopNet.Framework.Logging.csproj" />
  </ItemGroup>
</Project>