using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace R2.ShopNet.Framework.CQRS.SourceGenerator;

/// <summary>
/// Incremental source generator for CQRS handlers.
/// Automatically generates registration code for handlers marked with [GenerateHandler].
/// </summary>
[Generator]
public class CQRSHandlerGenerator : IIncrementalGenerator
{
    private const string GenerateHandlerAttributeName = "R2.ShopNet.Framework.CQRS.Attributes.GenerateHandlerAttribute";
    private const string CommandHandlerInterfaceName = "R2.ShopNet.Framework.CQRS.ICommandHandler";
    private const string QueryHandlerInterfaceName = "R2.ShopNet.Framework.CQRS.IQueryHandler";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Don't generate the attribute - it exists as a concrete class in the CQRS framework

        // Find all classes with [GenerateHandler] attribute
        var handlerDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateHandler(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null)!;

        // Combine and generate registration code
        var compilationAndHandlers = context.CompilationProvider.Combine(handlerDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndHandlers,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static bool IsCandidateHandler(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDeclaration &&
               classDeclaration.AttributeLists.Count > 0;
    }

    private static HandlerInfo? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration);

        if (symbol is not INamedTypeSymbol classSymbol)
            return null;

        // Check if has [GenerateHandler] attribute - be more lenient in matching
        var hasAttribute = classSymbol.GetAttributes()
            .Any(a => a.AttributeClass?.Name?.Contains("GenerateHandler") == true);

        if (!hasAttribute)
            return null;

        // Find handler interface - check for ICommandHandler or IQueryHandler
        INamedTypeSymbol? handlerInterface = null;
        HandlerType? handlerType = null;

        foreach (var iface in classSymbol.AllInterfaces)
        {
            var ifaceFullName = iface.ConstructedFrom.ToDisplayString();

            if (ifaceFullName.Contains("ICommandHandler"))
            {
                handlerInterface = iface;
                handlerType = HandlerType.Command;
                break;
            }
            else if (ifaceFullName.Contains("IQueryHandler"))
            {
                handlerInterface = iface;
                handlerType = HandlerType.Query;
                break;
            }
        }

        if (handlerInterface == null || handlerType == null)
            return null;

        var lifetime = GetLifetime(classSymbol);

        return new HandlerInfo(
            ClassName: classSymbol.ToDisplayString(),
            InterfaceName: handlerInterface.ToDisplayString(),
            Namespace: classSymbol.ContainingNamespace.ToDisplayString(),
            Lifetime: lifetime,
            Type: handlerType.Value);
    }

    private static string GetLifetime(INamedTypeSymbol classSymbol)
    {
        var attribute = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == GenerateHandlerAttributeName);

        if (attribute == null)
            return "Scoped";

        var lifetimeArg = attribute.NamedArguments.FirstOrDefault(kvp => kvp.Key == "Lifetime");
        if (lifetimeArg.Value.Value is int lifetimeValue)
        {
            return lifetimeValue switch
            {
                0 => "Singleton",
                1 => "Scoped",
                2 => "Transient",
                _ => "Scoped"
            };
        }

        return "Scoped";
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<HandlerInfo> handlers,
        SourceProductionContext context)
    {
        if (handlers.IsDefaultOrEmpty)
            return;

        var source = GenerateRegistrationCode(handlers);
        context.AddSource("CQRSHandlerRegistration.g.cs", source);
    }

    private static string GenerateRegistrationCode(ImmutableArray<HandlerInfo> handlers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using R2.ShopNet.Framework.CQRS;");
        sb.AppendLine();

        // Add namespaces for handlers
        var namespaces = handlers.Select(h => h.Namespace).Distinct().OrderBy(n => n);
        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace R2.ShopNet.Framework.CQRS.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated CQRS handler registration extensions.");
        sb.AppendLine("/// Generated at compile-time by R2.ShopNet.Framework.CQRS.SourceGenerator.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class GeneratedCQRSExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Registers {handlers.Length} CQRS handlers that were marked with [GenerateHandler].");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddGeneratedCQRSHandlers(this IServiceCollection services)");
        sb.AppendLine("    {");

        // Register dispatchers
        sb.AppendLine("        // Register dispatchers");
        sb.AppendLine("        services.AddScoped<ICommandDispatcher, CommandDispatcher>();");
        sb.AppendLine("        services.AddScoped<IQueryDispatcher, QueryDispatcher>();");
        sb.AppendLine();

        // Register handlers
        var commandHandlers = handlers.Where(h => h.Type == HandlerType.Command).ToList();
        var queryHandlers = handlers.Where(h => h.Type == HandlerType.Query).ToList();

        if (commandHandlers.Any())
        {
            sb.AppendLine($"        // Register {commandHandlers.Count} command handlers");
            foreach (var handler in commandHandlers)
            {
                sb.AppendLine($"        services.Add{handler.Lifetime}<{handler.InterfaceName}, {handler.ClassName}>();");
            }
            sb.AppendLine();
        }

        if (queryHandlers.Any())
        {
            sb.AppendLine($"        // Register {queryHandlers.Count} query handlers");
            foreach (var handler in queryHandlers)
            {
                sb.AppendLine($"        services.Add{handler.Lifetime}<{handler.InterfaceName}, {handler.ClassName}>();");
            }
            sb.AppendLine();
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate statistics method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets statistics about generated handlers.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static GeneratedHandlerStats GetGeneratedHandlerStats()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new GeneratedHandlerStats");
        sb.AppendLine("        {");
        sb.AppendLine($"            CommandHandlerCount = {commandHandlers.Count},");
        sb.AppendLine($"            QueryHandlerCount = {queryHandlers.Count},");
        sb.AppendLine($"            TotalHandlerCount = {handlers.Length}");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Generate stats class
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Statistics about generated CQRS handlers.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public record GeneratedHandlerStats");
        sb.AppendLine("{");
        sb.AppendLine("    public int CommandHandlerCount { get; init; }");
        sb.AppendLine("    public int QueryHandlerCount { get; init; }");
        sb.AppendLine("    public int TotalHandlerCount { get; init; }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateAttributeSource()
    {
        return @"// <auto-generated/>
#nullable enable

namespace R2.ShopNet.Framework.CQRS.Attributes
{
    /// <summary>
    /// Marks a command or query handler for automatic registration via source generation.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class GenerateHandlerAttribute : System.Attribute
    {
        /// <summary>
        /// Service lifetime for the handler registration (0=Singleton, 1=Scoped, 2=Transient).
        /// </summary>
        public int Lifetime { get; set; } = 1; // Scoped
    }
}
";
    }

    private record HandlerInfo(
        string ClassName,
        string InterfaceName,
        string Namespace,
        string Lifetime,
        HandlerType Type);

    private enum HandlerType
    {
        Command,
        Query
    }
}
