<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../R2.ShopNet.Catalog.Domain/R2.ShopNet.Catalog.Domain.csproj" />
    <ProjectReference Include="../../../Framework/R2.ShopNet.Framework.Common/R2.ShopNet.Framework.Common.csproj" />
    <ProjectReference Include="../../../Framework/R2.ShopNet.Framework.CQRS/R2.ShopNet.Framework.CQRS.csproj" />
    <ProjectReference Include="../../../Framework/R2.ShopNet.Framework.Events/R2.ShopNet.Framework.Events.csproj" />
    <ProjectReference Include="../../../Framework/R2.ShopNet.Framework.Persistence/R2.ShopNet.Framework.Persistence.csproj" />
  </ItemGroup>
</Project>